### ISSUE TITLE
Tracking of Future Site UI Design Implementations

### ISSUE THREAD

**Issue by LineIndent** [buridan-ui/ui#5]
## Tracking of Future Site UI Design Implementations

- [x] Fix site scaling issue (site developed 80 ~ 85 percent instead of 100).
- [x] Further improve landing page UI.
- [x] Change footer to ensure. consistency.
- [x] Refactor style classes, states, and other UI related code.
- [x] Improve component_wrapper for design wrapping.
- [x] Improve site theme (exp. background color).
- [ ] Refactor UI components for better readability.

## Component Sections List
- [x] Pantry Components.
- [x] Charts Components.
- [x] Interactive Apps.
- [x] Analytics Components [WIP]
- [x] Bluprint Templates [WIP]
